version: '{build}'
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore GitExtensions.PluginManager.sln
build:
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test .\test\PackageManager.NuGet.Tests\PackageManager.NuGet.Tests.csproj -c Release --no-build --test-adapter-path:. --logger:Appveyor /property:Platform=AnyCPU
    
    dotnet test .\test\PackageManager.Tests\PackageManager.Tests.csproj -c Release --no-build --test-adapter-path:. --logger:Appveyor /property:Platform=AnyCPU
